name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata (tags and labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-test:
    name: Build & Test (${{ matrix.sdk-and-framework.sdk }})
    runs-on: ubuntu-latest
    needs: build-docker-image
    container: ghcr.io/${{ github.repository }}:${{ needs.build-docker-image.outputs.tag || 'latest' }}
    strategy:
      fail-fast: false
      matrix:
        sdk-and-framework:
          - sdk: 8.x
            framework: net8.0
          - sdk: 9.x
            framework: net9.0
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show installed SDKs (debug)
        run: dotnet --info

      - name: Restore dependencies for all frameworks
        run: dotnet restore

      - name: Build Solution (target framework)
        run: |
          dotnet build ./Zentient.Codes.sln --no-restore --configuration Release --framework ${{ matrix.sdk-and-framework.framework }}

      - name: Run Tests (target framework)
        run: |
          dotnet test ./Zentient.Codes.sln --no-build --configuration Release --framework ${{ matrix.sdk-and-framework.framework }} --logger trx --results-directory TestResults

      - name: Upload Test Results for ${{ matrix.sdk-and-framework.sdk }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.sdk-and-framework.sdk }}
          path: TestResults

      - name: Report Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Tests (${{ matrix.sdk-and-framework.sdk }})
          path: "TestResults/*.trx"
          reporter: dotnet-trx
          github-token: ${{ secrets.GITHUB_TOKEN }}

  pack:
    name: Create Package (${{ matrix.sdk-and-framework.framework }})
    runs-on: ubuntu-latest
    needs: [build-and-test, build-docker-image]
    container: ghcr.io/${{ github.repository }}:${{ needs.build-docker-image.outputs.tag || 'latest' }}
    strategy:
      fail-fast: false
      matrix:
        sdk-and-framework:
          - sdk: 8.x
            framework: net8.0
          - sdk: 9.x
            framework: net9.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show installed SDKs (debug)
        run: dotnet --info

      - name: Restore (for pack)
        run: dotnet restore

      - name: Build and Pack (src only, skip tests)
        run: |
          mkdir -p out
          PROJECTS=$(find ./src -name "*.csproj")
          echo "Projects to consider for pack:"
          echo "$PROJECTS"

          for PROJECT_PATH in $PROJECTS; do
            if [[ "$PROJECT_PATH" == *".Tests."* ]] || [[ "$PROJECT_PATH" == *"/tests/"* ]] || [[ "$PROJECT_PATH" == *"/Test/"* ]]; then
              echo "Skipping test project: $PROJECT_PATH"
              continue
            fi

            IS_PACKABLE=$(dotnet msbuild "$PROJECT_PATH" -nologo -t:GetProperty -p:PropertyName=IsPackable 2>/dev/null | sed -n 's/.*IsPackable: //p' || true)
            if [[ -n "$IS_PACKABLE" && "$IS_PACKABLE" == "false" ]]; then
              echo "Project marked IsPackable=false, skipping: $PROJECT_PATH"
              continue
            fi

            echo "Building $PROJECT_PATH for ${{ matrix.sdk-and-framework.framework }}"
            dotnet build "$PROJECT_PATH" --no-restore --configuration Release --framework ${{ matrix.sdk-and-framework.framework }}

            echo "Packing $PROJECT_PATH for target ${{ matrix.sdk-and-framework.framework }}"
            dotnet pack "$PROJECT_PATH" --no-restore --no-build --configuration Release -o out --property:TargetFramework=${{ matrix.sdk-and-framework.framework }}
          done

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages-${{ matrix.sdk-and-framework.framework }}
          path: out/*.nupkg

  publish-staging:
    name: Publish to GitHub Packages (Staging)
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    container: ghcr.io/${{ github.repository }}:${{ needs.build-docker-image.outputs.tag || 'latest' }}
    steps:
      - name: Download all package artifacts
        uses: actions/download-artifact@v4
        with:
          path: out

      - name: Push to GitHub Packages
        run: dotnet nuget push "out/**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'release'
    container: ghcr.io/${{ github.repository }}:${{ needs.build-docker-image.outputs.tag || 'latest' }}
    steps:
      - name: Download all package artifacts
        uses: actions/download-artifact@v4
        with:
          path: out

      - name: Push to NuGet
        run: dotnet nuget push "out/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
